<img src="https://raw.githubusercontent.com/rhatiro/Curso_EBAC-Profissao_Cientista_de_Dados/main/ebac-course-utils/media/logo/newebac_logo_black_half.png" alt="ebac-logo">

---

# **Profissão: Cientista de Dados**
### **Módulo 9** | Exercício 1

Aluno [Lays Félix](https://www.linkedin.com/in/laysfelixbusiness)<br>
Data: 17 de janeiro de 2023

---

# 1. Importando bibliotecas <a name="import"></a>

<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [1]:
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

%matplotlib inline

# 2. Carregando o dataframe SINASC <a name="read"></a>
<div style="text-align: right"
     
[Voltar ao índice](#Contents)

In [2]:
sinasc_raw = pd.read_csv('RO_2019.csv')
sinasc_raw.head()

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,KOTELCHUCK,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea
0,1,2679477.0,110001,1,19,5.0,8 a 11 anos,NaN,0.0,0.0,...,5,1,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
1,1,2679477.0,110001,1,29,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,2,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
2,1,2679477.0,110001,1,37,9.0,8 a 11 anos,513205.0,2.0,0.0,...,5,3,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
3,1,2516500.0,110001,1,30,5.0,12 anos ou mais,231205.0,0.0,0.0,...,4,4,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia,-12.13178,-61.85308,397.0,3958.273
4,1,2516500.0,110001,1,30,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,5,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025

# Tarefa 1

### 1. Idade media das mães e dos pais por município (coluna munResNome)

In [3]:
# Selecionando só as colunas que preciso

sinasc_1 = sinasc_raw[['munResNome', 'IDADEMAE','IDADEPAI']]
sinasc_1.head()

                munResNome  IDADEMAE  IDADEPAI
0    Alta Floresta D'Oeste        19      26.0
1    Alta Floresta D'Oeste        29      24.0
2    Alta Floresta D'Oeste        37      32.0
3  Alto Alegre dos Parecis        30      24.0
4    Alta Floresta D'Oeste        30      27.0

In [44]:
# Fazendo a média das idades dos pais por município

sinasc_1.groupby('munResNome').mean()

                            IDADEMAE   IDADEPAI
munResNome
Alta Floresta D'Oeste      25.991826  29.548701
Alto Alegre dos Parecis    24.844156  29.179104
Alto Paraíso               24.960177  28.833333
Alvorada D'Oeste           25.770732  30.757282
Ariquemes                  25.607866  32.466667
Buritis                    25.559177  30.812500
Cabixi                     26.037500  34.333333
Cacaulândia                25.546667  36.333333
Cacoal                     26.890102  30.931854
Campo Novo de Rondônia     24.825301  30.500000
Candeias do Jamari         25.243323  29.894737
Castanheiras               27.281250  30.392857
Cerejeiras                 27.240506  31.652778
Chupinguaia                25.333333  29.629630
Colorado do Oeste          27.602804  34.354839
Corumbiara                 24.716535  32.470588
Costa Marques              24.412017  30.613636
Cujubim                    24.482927  31.400000
Espigão D'Oeste            26.093333  31.198113
Governador Jorge Teixeira  24.401786  29.222222
Guajará-Mirim              25.462228  30.470588
Itapuã do Oeste            26.064220  42.500000
Jaru                       25.982974  32.197183
Ji-Paraná                  26.361137  31.132239
Machadinho D'Oeste         25.480000  31.326923
Ministro Andreazza         27.904762  33.849315
Mirante da Serra           26.304878  32.154762
Monte Negro                25.648241  34.678571
Município ignorado - RO    24.000000  22.000000
Nova Brasilândia D'Oeste   26.222222  30.520833
Nova Mamoré                25.326389  31.692308
Nova União                 26.894231  31.371429
Novo Horizonte do Oeste    26.938776  31.588235
Ouro Preto do Oeste        26.375594  31.233244
Parecis                    26.454545  32.473684
Pimenta Bueno              25.199675  29.745174
Pimenteiras do Oeste       25.075000  35.600000
Porto Velho                26.312670  32.352679
Presidente Médici          25.796053  30.150754
Primavera de Rondônia      27.023256  31.888889
Rio Crespo                 26.660000  28.000000
Rolim de Moura             26.600863  30.360479
Santa Luzia D'Oeste        26.121212  30.703297
Seringueiras               24.910714  30.500000
São Felipe D'Oeste         26.481481  31.395833
São Francisco do Guaporé   25.660066  31.638889
São Miguel do Guaporé      25.926346  32.666667
Teixeirópolis              26.031250  31.500000
Theobroma                  25.536082  30.083333
Urupá                      26.688235  31.008929
Vale do Anari              26.096774  34.000000
Vale do Paraíso            25.679012  29.976744
Vilhena                    26.433962  34.152941

### 2. Peso médio dos bebes por sexo que nasceram no dia do seu aniversário por faixas de escolaridade mae
Ex: Você, aluna(o), nasceu no dia 10/01, então você precisa filtrar o conjunto de dados nessa data e calcular o peso médio dos bebês de cada sexo por faixa de escolaridade da mãe.

In [5]:
# Selecionando só as colunas que preciso

sinasc_2 = sinasc_raw[['PESO', 'SEXO', 'DTNASC', 'ESCMAE']]
sinasc_2.head()

   PESO       SEXO      DTNASC           ESCMAE
0  3685  Masculino  2019-02-19      8 a 11 anos
1  3055   Feminino  2019-02-21      8 a 11 anos
2  3460   Feminino  2019-02-25      8 a 11 anos
3  2982   Feminino  2019-03-20  12 anos ou mais
4  3310   Feminino  2019-03-23      8 a 11 anos

In [6]:
# Criei um nova DF só com 'DTNASC' == '2019-10-16'

niver = sinasc_2[sinasc_2['DTNASC'] == '2019-10-16']
niver

       PESO       SEXO      DTNASC           ESCMAE
13799  3240  Masculino  2019-10-16  12 anos ou mais
14470  3560   Feminino  2019-10-16      8 a 11 anos
14521  3410  Masculino  2019-10-16  12 anos ou mais
14522  3405  Masculino  2019-10-16  12 anos ou mais
14561  2150  Masculino  2019-10-16  12 anos ou mais
...     ...        ...         ...              ...
26361  3930   Feminino  2019-10-16      8 a 11 anos
26362  3780  Masculino  2019-10-16      8 a 11 anos
26384  3290   Feminino  2019-10-16       4 a 7 anos
26582  4005   Feminino  2019-10-16      8 a 11 anos
26708  2830   Feminino  2019-10-16  12 anos ou mais

[85 rows x 4 columns]

In [7]:
# Peso médio dos bebes por sexo que nasceram no meu niver por faixas de escolaridade mae

niver.groupby(['ESCMAE', 'SEXO'])['PESO'].mean().unstack()

SEXO                Feminino    Masculino
ESCMAE
1 a 3 anos       2800.000000          NaN
12 anos ou mais  3096.500000  3105.000000
4 a 7 anos       3374.166667  3203.888889
8 a 11 anos      3331.464286  3431.052632

In [8]:
# Mesmo comando, porém sem unstack. 
# Observe que não exibe dados para Masculino na ESCMAE = 1 a 3 anos, confirmando o "NaN" acima.

niver.groupby(['ESCMAE', 'SEXO'])['PESO'].mean()

ESCMAE           SEXO
1 a 3 anos       Feminino     2800.000000
12 anos ou mais  Feminino     3096.500000
                 Masculino    3105.000000
4 a 7 anos       Feminino     3374.166667
                 Masculino    3203.888889
8 a 11 anos      Feminino     3331.464286
                 Masculino    3431.052632
Name: PESO, dtype: float64

In [9]:
# Como exemplo, executando o mesmo comando, porém consultando tada a base

sinasc_2.groupby(['ESCMAE', 'SEXO'])['PESO'].mean()

ESCMAE           SEXO
1 a 3 anos       Feminino     3126.363636
                 Masculino    3191.354386
12 anos ou mais  Feminino     3182.427912
                 Masculino    3309.658421
4 a 7 anos       Feminino     3158.036123
                 Masculino    3288.963439
8 a 11 anos      Feminino     3193.250588
                 Masculino    3305.898320
Nenhuma          Feminino     2972.333333
                 Masculino    3178.181818
Name: PESO, dtype: float64

### 3. Qual o municipio que nasceu menos bebe em 2019?
    - qual a idade media, maxima, minima das maes nesse municipio?
    - qual a idade media, maxima, minima dos pais nesse municipio?

In [12]:
sinasc_raw.munResNome.value_counts()

Porto Velho                  8437
Ji-Paraná                    2182
Ariquemes                    1729
Vilhena                      1590
Cacoal                       1374
Rolim de Moura                927
Jaru                          881
Guajará-Mirim                 781
Ouro Preto do Oeste           631
Pimenta Bueno                 616
Buritis                       583
Machadinho D'Oeste            500
Espigão D'Oeste               450
Nova Mamoré                   432
Alta Floresta D'Oeste         367
São Miguel do Guaporé         353
Candeias do Jamari            337
Presidente Médici             304
São Francisco do Guaporé      303
Nova Brasilândia D'Oeste      261
Cerejeiras                    237
Costa Marques                 233
Alto Paraíso                  226
Colorado do Oeste             214
Alvorada D'Oeste              205
Cujubim                       205
Monte Negro                   199
Urupá                         170
Seringueiras                  168
Campo Novo de Rondônia        166
Mirante da Serra              164
Chupinguaia                   162
Alto Alegre dos Parecis       154
Corumbiara                    127
Governador Jorge Teixeira     112
Itapuã do Oeste               109
Nova União                    104
Santa Luzia D'Oeste            99
Novo Horizonte do Oeste        98
Theobroma                      97
Vale do Anari                  93
Ministro Andreazza             84
Vale do Paraíso                81
Cabixi                         80
Cacaulândia                    75
Teixeirópolis                  64
São Felipe D'Oeste             54
Rio Crespo                     50
Parecis                        44
Primavera de Rondônia          43
Pimenteiras do Oeste           40
Castanheiras                   32
Município ignorado - RO         1
Name: munResNome, dtype: int64

Resposta: desconsiderando o município 'Município ignorado - RO'
### Castanheiras

In [13]:
# Criei um nova DF só com dados do municípo 'Castanheiras'

menor_nasc = sinasc_raw[sinasc_raw['munResNome'] == 'Castanheiras']
menor_nasc

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,KOTELCHUCK,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea
2067,1,2496046.0,110004,1,18,1.0,8 a 11 anos,999992.0,0.0,0.0,...,3,2087,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
2300,1,7648693.0,110004,1,31,5.0,8 a 11 anos,999992.0,0.0,0.0,...,5,2323,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
4512,1,2495279.0,110012,1,22,1.0,8 a 11 anos,521135.0,0.0,0.0,...,2,4538,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
5881,1,2516047.0,110018,1,26,2.0,8 a 11 anos,NaN,0.0,0.0,...,5,5913,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
5952,1,2516047.0,110018,1,32,1.0,12 anos ou mais,NaN,2.0,0.0,...,5,5984,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
10762,1,2495228.0,110028,1,21,1.0,8 a 11 anos,621005.0,0.0,0.0,...,5,10842,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
10768,1,2495228.0,110028,1,31,5.0,8 a 11 anos,621005.0,1.0,0.0,...,5,10848,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
10882,1,2495228.0,110028,1,23,2.0,8 a 11 anos,999992.0,0.0,0.0,...,5,10963,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
10962,1,2495228.0,110028,1,29,1.0,8 a 11 anos,621005.0,3.0,0.0,...,5,11043,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
10988,1,2495228.0,110028,1,31,2.0,8 a 11 anos,999992.0,1.0,1.0,...,5,11069,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
10997,1,2495228.0,110028,1,35,4.0,8 a 11 anos,621005.0,2.0,0.0,...,5,11078,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
11017,1,2495228.0,110028,1,27,1.0,12 anos ou mais,251605.0,1.0,0.0,...,5,11098,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
11175,1,2495228.0,110028,1,24,1.0,4 a 7 anos,999992.0,2.0,0.0,...,4,11256,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
11196,1,2495228.0,110028,1,27,2.0,4 a 7 anos,621005.0,1.0,0.0,...,3,11277,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
11293,1,2495228.0,110028,1,25,1.0,8 a 11 anos,621005.0,2.0,1.0,...,5,11374,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
11354,1,2516594.0,110028,1,34,5.0,12 anos ou mais,621005.0,1.0,0.0,...,2,11435,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
11371,1,2495228.0,110028,1,21,5.0,8 a 11 anos,421125.0,0.0,0.0,...,5,11452,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
17441,1,3152928.0,110012,1,39,2.0,12 anos ou mais,252105.0,0.0,0.0,...,5,1483994,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24282,1,2495228.0,110028,1,28,5.0,8 a 11 anos,621005.0,1.0,0.0,...,9,1490901,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24288,1,2495228.0,110028,1,27,2.0,8 a 11 anos,621005.0,2.0,0.0,...,5,1490907,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24299,1,2495228.0,110028,1,30,2.0,4 a 7 anos,999992.0,2.0,0.0,...,5,1490918,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24316,1,2495228.0,110028,1,17,5.0,4 a 7 anos,999992.0,0.0,0.0,...,4,1490935,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24486,1,2495228.0,110028,1,35,1.0,4 a 7 anos,999992.0,6.0,1.0,...,2,1491105,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24507,1,2495228.0,110028,1,27,5.0,8 a 11 anos,621005.0,1.0,0.0,...,5,1491127,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24517,1,2495228.0,110028,1,27,5.0,12 anos ou mais,422105.0,0.0,0.0,...,5,1491137,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24528,1,2495228.0,110028,1,25,1.0,8 a 11 anos,621005.0,0.0,0.0,...,5,1491148,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24605,1,2495228.0,110028,1,32,2.0,8 a 11 anos,621005.0,0.0,0.0,...,5,1491225,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24639,1,2495228.0,110028,1,18,1.0,4 a 7 anos,621005.0,0.0,0.0,...,5,1491259,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24674,1,2495228.0,110028,1,27,1.0,8 a 11 anos,999992.0,1.0,0.0,...,5,1491294,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24715,1,2495228.0,110028,1,32,2.0,8 a 11 anos,621005.0,1.0,0.0,...,5,1491335,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24781,1,2495228.0,110028,1,22,2.0,8 a 11 anos,621005.0,2.0,0.0,...,9,1491401,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24863,1,2495228.0,110028,1,30,5.0,8 a 11 anos,621005.0,2.0,0.0,...,4,1491483,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842

In [14]:
# Selecionando as colunas necessárias para tratar os dados a fim de realizar a consulta solicitada

menor_nasc[['munResNome','IDADEMAE', 'IDADEPAI']]
menor_nasc

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,KOTELCHUCK,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea
2067,1,2496046.0,110004,1,18,1.0,8 a 11 anos,999992.0,0.0,0.0,...,3,2087,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
2300,1,7648693.0,110004,1,31,5.0,8 a 11 anos,999992.0,0.0,0.0,...,5,2323,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
4512,1,2495279.0,110012,1,22,1.0,8 a 11 anos,521135.0,0.0,0.0,...,2,4538,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
5881,1,2516047.0,110018,1,26,2.0,8 a 11 anos,NaN,0.0,0.0,...,5,5913,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
5952,1,2516047.0,110018,1,32,1.0,12 anos ou mais,NaN,2.0,0.0,...,5,5984,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
10762,1,2495228.0,110028,1,21,1.0,8 a 11 anos,621005.0,0.0,0.0,...,5,10842,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
10768,1,2495228.0,110028,1,31,5.0,8 a 11 anos,621005.0,1.0,0.0,...,5,10848,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
10882,1,2495228.0,110028,1,23,2.0,8 a 11 anos,999992.0,0.0,0.0,...,5,10963,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
10962,1,2495228.0,110028,1,29,1.0,8 a 11 anos,621005.0,3.0,0.0,...,5,11043,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
10988,1,2495228.0,110028,1,31,2.0,8 a 11 anos,999992.0,1.0,1.0,...,5,11069,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
10997,1,2495228.0,110028,1,35,4.0,8 a 11 anos,621005.0,2.0,0.0,...,5,11078,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
11017,1,2495228.0,110028,1,27,1.0,12 anos ou mais,251605.0,1.0,0.0,...,5,11098,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
11175,1,2495228.0,110028,1,24,1.0,4 a 7 anos,999992.0,2.0,0.0,...,4,11256,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
11196,1,2495228.0,110028,1,27,2.0,4 a 7 anos,621005.0,1.0,0.0,...,3,11277,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
11293,1,2495228.0,110028,1,25,1.0,8 a 11 anos,621005.0,2.0,1.0,...,5,11374,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
11354,1,2516594.0,110028,1,34,5.0,12 anos ou mais,621005.0,1.0,0.0,...,2,11435,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
11371,1,2495228.0,110028,1,21,5.0,8 a 11 anos,421125.0,0.0,0.0,...,5,11452,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
17441,1,3152928.0,110012,1,39,2.0,12 anos ou mais,252105.0,0.0,0.0,...,5,1483994,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24282,1,2495228.0,110028,1,28,5.0,8 a 11 anos,621005.0,1.0,0.0,...,9,1490901,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24288,1,2495228.0,110028,1,27,2.0,8 a 11 anos,621005.0,2.0,0.0,...,5,1490907,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24299,1,2495228.0,110028,1,30,2.0,4 a 7 anos,999992.0,2.0,0.0,...,5,1490918,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24316,1,2495228.0,110028,1,17,5.0,4 a 7 anos,999992.0,0.0,0.0,...,4,1490935,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24486,1,2495228.0,110028,1,35,1.0,4 a 7 anos,999992.0,6.0,1.0,...,2,1491105,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24507,1,2495228.0,110028,1,27,5.0,8 a 11 anos,621005.0,1.0,0.0,...,5,1491127,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24517,1,2495228.0,110028,1,27,5.0,12 anos ou mais,422105.0,0.0,0.0,...,5,1491137,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24528,1,2495228.0,110028,1,25,1.0,8 a 11 anos,621005.0,0.0,0.0,...,5,1491148,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24605,1,2495228.0,110028,1,32,2.0,8 a 11 anos,621005.0,0.0,0.0,...,5,1491225,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24639,1,2495228.0,110028,1,18,1.0,4 a 7 anos,621005.0,0.0,0.0,...,5,1491259,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24674,1,2495228.0,110028,1,27,1.0,8 a 11 anos,999992.0,1.0,0.0,...,5,1491294,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24715,1,2495228.0,110028,1,32,2.0,8 a 11 anos,621005.0,1.0,0.0,...,5,1491335,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24781,1,2495228.0,110028,1,22,2.0,8 a 11 anos,621005.0,2.0,0.0,...,9,1491401,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842
24863,1,2495228.0,110028,1,30,5.0,8 a 11 anos,621005.0,2.0,0.0,...,4,1491483,ATIVO,MUNIC,Castanheiras,Rondônia,-11.42684,-61.94916,215.0,892.842

In [15]:
#Realiando a cópia do DF menor_nasc só com os dados necessários para tratar NaN
castanheiras = menor_nasc[['munResNome','IDADEMAE', 'IDADEPAI']].copy()
castanheiras

         munResNome  IDADEMAE  IDADEPAI
2067   Castanheiras        18      17.0
2300   Castanheiras        31      36.0
4512   Castanheiras        22       NaN
5881   Castanheiras        26      24.0
5952   Castanheiras        32      29.0
10762  Castanheiras        21      19.0
10768  Castanheiras        31      31.0
10882  Castanheiras        23      25.0
10962  Castanheiras        29      32.0
10988  Castanheiras        31      42.0
10997  Castanheiras        35      38.0
11017  Castanheiras        27      32.0
11175  Castanheiras        24      28.0
11196  Castanheiras        27      35.0
11293  Castanheiras        25      29.0
11354  Castanheiras        34      38.0
11371  Castanheiras        21       NaN
17441  Castanheiras        39      43.0
24282  Castanheiras        28      29.0
24288  Castanheiras        27      35.0
24299  Castanheiras        30      35.0
24316  Castanheiras        17       NaN
24486  Castanheiras        35      38.0
24507  Castanheiras        27      27.0
24517  Castanheiras        27      20.0
24528  Castanheiras        25      32.0
24605  Castanheiras        32      25.0
24639  Castanheiras        18      27.0
24674  Castanheiras        27       NaN
24715  Castanheiras        32      33.0
24781  Castanheiras        22      19.0
24863  Castanheiras        30      33.0

In [16]:
# Eliminando linhas com missing para fazer Média

castanheiras.dropna(inplace=True)

In [17]:
castanheiras.IDADEPAI.isnull().sum()

0

In [18]:
castanheiras.shape

(28, 3)

In [20]:
castanheiras

         munResNome  IDADEMAE  IDADEPAI
2067   Castanheiras        18      17.0
2300   Castanheiras        31      36.0
5881   Castanheiras        26      24.0
5952   Castanheiras        32      29.0
10762  Castanheiras        21      19.0
10768  Castanheiras        31      31.0
10882  Castanheiras        23      25.0
10962  Castanheiras        29      32.0
10988  Castanheiras        31      42.0
10997  Castanheiras        35      38.0
11017  Castanheiras        27      32.0
11175  Castanheiras        24      28.0
11196  Castanheiras        27      35.0
11293  Castanheiras        25      29.0
11354  Castanheiras        34      38.0
17441  Castanheiras        39      43.0
24282  Castanheiras        28      29.0
24288  Castanheiras        27      35.0
24299  Castanheiras        30      35.0
24486  Castanheiras        35      38.0
24507  Castanheiras        27      27.0
24517  Castanheiras        27      20.0
24528  Castanheiras        25      32.0
24605  Castanheiras        32      25.0
24639  Castanheiras        18      27.0
24715  Castanheiras        32      33.0
24781  Castanheiras        22      19.0
24863  Castanheiras        30      33.0

In [21]:
# Qual a idade media, maxima, minima das maes nesse municipio?
# Qual a idade media, maxima, minima dos pais nesse municipio?

agrupamento = castanheiras.groupby(['munResNome'])
agrupamento.agg([('Média','mean'), ('Máximo','max'), ('Mínimo','min')])

               IDADEMAE                 IDADEPAI
                  Média Máximo Mínimo      Média Máximo Mínimo
munResNome
Castanheiras  28.071429     39     18  30.392857   43.0   17.0

### 4. Qual o municipio que nasceu mais bebe no mês de março?
    a) qual a quantidade de filhos vivos media, maxima, minima nesse municipio?
    b) qual a idade media, maxima, minima dos pais nesse municipio?

In [22]:
#Criando DF com os dados do mês de março

selecao = (sinasc_raw['DTNASC'] >= '2019-03-01') & (sinasc_raw['DTNASC'] <= '2019-03-31')
marco = sinasc_raw[selecao]

In [23]:
marco

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,KOTELCHUCK,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea
3,1,2516500.0,110001,1,30,5.0,12 anos ou mais,231205.0,0.0,0.0,...,4,4,ATIVO,MUNIC,Alto Alegre dos Parecis,Rondônia,-12.13178,-61.85308,397.0,3958.273
4,1,2516500.0,110001,1,30,2.0,8 a 11 anos,999992.0,1.0,0.0,...,5,5,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
5,1,2516500.0,110001,1,33,5.0,1 a 3 anos,621005.0,2.0,1.0,...,5,6,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
9,1,2679477.0,110001,1,30,2.0,1 a 3 anos,999992.0,1.0,1.0,...,5,10,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
10,1,2679477.0,110001,1,31,5.0,8 a 11 anos,512105.0,1.0,0.0,...,5,11,ATIVO,MUNIC,Alta Floresta D'Oeste,Rondônia,-11.93554,-61.99982,338.0,7067.025
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13670,1,2000733.0,120040,1,24,5.0,8 a 11 anos,999992.0,0.0,0.0,...,5,18687,ATIVO,MUNIC,Porto Velho,Rondônia,-8.76889,-63.83145,87.0,34096.394
13671,1,2000733.0,120040,1,24,5.0,4 a 7 anos,999992.0,2.0,0.0,...,9,18702,ATIVO,MUNIC,Porto Velho,Rondônia,-8.76889,-63.83145,87.0,34096.394
13736,1,2688611.0,355030,1,35,2.0,12 anos ou mais,10210.0,1.0,0.0,...,5,1066018,ATIVO,MUNIC,Porto Velho,Rondônia,-8.76889,-63.83145,87.0,34096.394
13748,1,2311682.0,510340,1,36,4.0,12 anos ou mais,354605.0,2.0,1.0,...,5,1386627,ATIVO,MUNIC,Vilhena,Rondônia,-12.74137,-60.13858,595.0,11518.915
13750,1,2604388.0,510340,1,31,2.0,12 anos ou mais,142305.0,0.0,1.0,...,5,1388221,ATIVO,MUNIC,Ji-Paraná,Rondônia,-10.88205,-61.94509,157.0,6896.648

In [28]:
# Consultando qual município teve mais nascimentos - Essa consulta exibe só o valor

marco.munResNome.value_counts().max()

744

In [29]:
# Consultando qual município teve mais nascimentos

marco.munResNome.value_counts()

Porto Velho                  744
Ji-Paraná                    188
Vilhena                      148
Ariquemes                    141
Cacoal                       133
Jaru                          80
Guajará-Mirim                 75
Rolim de Moura                69
Ouro Preto do Oeste           67
Pimenta Bueno                 62
Buritis                       59
Nova Mamoré                   53
Machadinho D'Oeste            44
Espigão D'Oeste               44
São Miguel do Guaporé         41
Candeias do Jamari            33
São Francisco do Guaporé      31
Alta Floresta D'Oeste         31
Presidente Médici             29
Costa Marques                 24
Alto Paraíso                  22
Alvorada D'Oeste              22
Monte Negro                   20
Nova Brasilândia D'Oeste      20
Seringueiras                  19
Colorado do Oeste             19
Chupinguaia                   18
Cujubim                       17
Cerejeiras                    16
Urupá                         14
Vale do Paraíso               13
Campo Novo de Rondônia        13
Corumbiara                    12
Vale do Anari                 11
Governador Jorge Teixeira     10
Alto Alegre dos Parecis       10
Cacaulândia                   10
Mirante da Serra               9
Rio Crespo                     9
Theobroma                      8
Itapuã do Oeste                8
Santa Luzia D'Oeste            7
Nova União                     7
Pimenteiras do Oeste           6
Cabixi                         6
Parecis                        6
Ministro Andreazza             6
Primavera de Rondônia          5
Novo Horizonte do Oeste        5
São Felipe D'Oeste             5
Castanheiras                   4
Teixeirópolis                  3
Name: munResNome, dtype: int64

### Qual o municipio que nasceu mais bebe no mês de março?
    - Porto Velho

In [31]:
#Criando DF somente com o município com mais nascimentos no mês de março

selecao = (marco['munResNome'] == 'Porto Velho') & (marco['DTNASC'])
marco_2 = marco[selecao]
marco_2

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,KOTELCHUCK,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea
612,1,2494299.0,110002,1,19,5.0,4 a 7 anos,999992.0,0.0,0.0,...,3,618,ATIVO,MUNIC,Porto Velho,Rondônia,-8.76889,-63.83145,87.0,34096.394
700,1,2494299.0,110002,1,19,5.0,4 a 7 anos,622020.0,1.0,0.0,...,4,706,ATIVO,MUNIC,Porto Velho,Rondônia,-8.76889,-63.83145,87.0,34096.394
3232,1,2808609.0,110011,1,34,5.0,Nenhuma,622020.0,0.0,1.0,...,4,3257,ATIVO,MUNIC,Porto Velho,Rondônia,-8.76889,-63.83145,87.0,34096.394
3238,1,2808609.0,110011,1,24,5.0,8 a 11 anos,622020.0,1.0,0.0,...,5,3263,ATIVO,MUNIC,Porto Velho,Rondônia,-8.76889,-63.83145,87.0,34096.394
6818,1,2515369.0,110020,1,38,2.0,12 anos ou mais,999991.0,2.0,1.0,...,5,6864,ATIVO,MUNIC,Porto Velho,Rondônia,-8.76889,-63.83145,87.0,34096.394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13668,1,2000733.0,120040,1,19,5.0,4 a 7 anos,999992.0,1.0,0.0,...,3,18630,ATIVO,MUNIC,Porto Velho,Rondônia,-8.76889,-63.83145,87.0,34096.394
13669,1,2000733.0,120040,1,21,5.0,4 a 7 anos,999992.0,0.0,0.0,...,9,18667,ATIVO,MUNIC,Porto Velho,Rondônia,-8.76889,-63.83145,87.0,34096.394
13670,1,2000733.0,120040,1,24,5.0,8 a 11 anos,999992.0,0.0,0.0,...,5,18687,ATIVO,MUNIC,Porto Velho,Rondônia,-8.76889,-63.83145,87.0,34096.394
13671,1,2000733.0,120040,1,24,5.0,4 a 7 anos,999992.0,2.0,0.0,...,9,18702,ATIVO,MUNIC,Porto Velho,Rondônia,-8.76889,-63.83145,87.0,34096.394
13736,1,2688611.0,355030,1,35,2.0,12 anos ou mais,10210.0,1.0,0.0,...,5,1066018,ATIVO,MUNIC,Porto Velho,Rondônia,-8.76889,-63.83145,87.0,34096.394

In [32]:
# Qual a quantidade de filhos vivos media, maxima, minima nesse municipio?

In [33]:
marco_2.groupby('munResNome')['QTDFILVIVO'].count()

munResNome
Porto Velho    627
Name: QTDFILVIVO, dtype: int64

In [35]:
tarefa_4 = marco_2[['QTDFILVIVO', 'DTNASC']].copy()
tarefa_4

       QTDFILVIVO      DTNASC
612           0.0  2019-03-09
700           1.0  2019-03-28
3232          0.0  2019-03-11
3238          1.0  2019-03-13
6818          2.0  2019-03-01
...           ...         ...
13668         1.0  2019-03-20
13669         0.0  2019-03-25
13670         0.0  2019-03-21
13671         2.0  2019-03-22
13736         1.0  2019-03-07

[744 rows x 2 columns]

In [36]:
resultado = tarefa_4.groupby('DTNASC')['QTDFILVIVO'].count()
resultado

DTNASC
2019-03-01    31
2019-03-02    23
2019-03-03    10
2019-03-04    15
2019-03-05    23
2019-03-06    14
2019-03-07    12
2019-03-08    17
2019-03-09    15
2019-03-10    14
2019-03-11    27
2019-03-12    15
2019-03-13    18
2019-03-14    16
2019-03-15    31
2019-03-16    21
2019-03-17    16
2019-03-18    25
2019-03-19    17
2019-03-20    19
2019-03-21    26
2019-03-22    18
2019-03-23    19
2019-03-24    22
2019-03-25    24
2019-03-26    23
2019-03-27    25
2019-03-28    30
2019-03-29    25
2019-03-30    19
2019-03-31    17
Name: QTDFILVIVO, dtype: int64

In [37]:
# Média da quantidade de filhos vivos por dia do mês de março ordenado pela data de nascimento

tarefa_4.groupby('DTNASC', sort=True)['QTDFILVIVO'].mean().to_frame()

            QTDFILVIVO
DTNASC
2019-03-01    1.322581
2019-03-02    1.434783
2019-03-03    1.400000
2019-03-04    1.600000
2019-03-05    1.652174
2019-03-06    1.285714
2019-03-07    1.416667
2019-03-08    1.588235
2019-03-09    1.000000
2019-03-10    1.214286
2019-03-11    1.222222
2019-03-12    1.533333
2019-03-13    1.222222
2019-03-14    1.562500
2019-03-15    1.193548
2019-03-16    1.523810
2019-03-17    1.562500
2019-03-18    1.600000
2019-03-19    1.235294
2019-03-20    1.315789
2019-03-21    1.153846
2019-03-22    0.944444
2019-03-23    1.000000
2019-03-24    0.818182
2019-03-25    1.041667
2019-03-26    1.217391
2019-03-27    1.960000
2019-03-28    0.933333
2019-03-29    1.080000
2019-03-30    1.789474
2019-03-31    0.588235

In [38]:
# Média, Mínimo e Máximo de fihos vivos por dia do mês de março

agrupamento = tarefa_4.groupby(['DTNASC'])
agrupamento.agg([('Média','mean'), ('Máximo','max'), ('Mínimo','min')])

           QTDFILVIVO
                Média Máximo Mínimo
DTNASC
2019-03-01   1.322581    3.0    0.0
2019-03-02   1.434783    4.0    0.0
2019-03-03   1.400000    3.0    0.0
2019-03-04   1.600000    4.0    0.0
2019-03-05   1.652174    5.0    0.0
2019-03-06   1.285714    4.0    0.0
2019-03-07   1.416667    7.0    0.0
2019-03-08   1.588235    4.0    0.0
2019-03-09   1.000000    2.0    0.0
2019-03-10   1.214286    3.0    0.0
2019-03-11   1.222222    4.0    0.0
2019-03-12   1.533333    5.0    0.0
2019-03-13   1.222222    5.0    0.0
2019-03-14   1.562500    6.0    0.0
2019-03-15   1.193548    4.0    0.0
2019-03-16   1.523810    6.0    0.0
2019-03-17   1.562500    3.0    0.0
2019-03-18   1.600000    6.0    0.0
2019-03-19   1.235294    4.0    0.0
2019-03-20   1.315789    6.0    0.0
2019-03-21   1.153846    5.0    0.0
2019-03-22   0.944444    2.0    0.0
2019-03-23   1.000000    6.0    0.0
2019-03-24   0.818182    2.0    0.0
2019-03-25   1.041667    9.0    0.0
2019-03-26   1.217391    5.0    0.0
2019-03-27   1.960000    6.0    0.0
2019-03-28   0.933333    4.0    0.0
2019-03-29   1.080000    5.0    0.0
2019-03-30   1.789474    5.0    0.0
2019-03-31   0.588235    2.0    0.0

In [39]:
# Qual a idade media, maxima, minima dos pais nesse municipio?

In [40]:

selecao = (marco['munResNome'] == 'Porto Velho') & (marco['DTNASC'])
marco_2 = marco[selecao]
marco_2

,ORIGEM,CODESTAB,CODMUNNASC,LOCNASC,IDADEMAE,ESTCIVMAE,ESCMAE,CODOCUPMAE,QTDFILVIVO,QTDFILMORT,...,KOTELCHUCK,CONTADOR,munResStatus,munResTipo,munResNome,munResUf,munResLat,munResLon,munResAlt,munResArea
612,1,2494299.0,110002,1,19,5.0,4 a 7 anos,999992.0,0.0,0.0,...,3,618,ATIVO,MUNIC,Porto Velho,Rondônia,-8.76889,-63.83145,87.0,34096.394
700,1,2494299.0,110002,1,19,5.0,4 a 7 anos,622020.0,1.0,0.0,...,4,706,ATIVO,MUNIC,Porto Velho,Rondônia,-8.76889,-63.83145,87.0,34096.394
3232,1,2808609.0,110011,1,34,5.0,Nenhuma,622020.0,0.0,1.0,...,4,3257,ATIVO,MUNIC,Porto Velho,Rondônia,-8.76889,-63.83145,87.0,34096.394
3238,1,2808609.0,110011,1,24,5.0,8 a 11 anos,622020.0,1.0,0.0,...,5,3263,ATIVO,MUNIC,Porto Velho,Rondônia,-8.76889,-63.83145,87.0,34096.394
6818,1,2515369.0,110020,1,38,2.0,12 anos ou mais,999991.0,2.0,1.0,...,5,6864,ATIVO,MUNIC,Porto Velho,Rondônia,-8.76889,-63.83145,87.0,34096.394
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
13668,1,2000733.0,120040,1,19,5.0,4 a 7 anos,999992.0,1.0,0.0,...,3,18630,ATIVO,MUNIC,Porto Velho,Rondônia,-8.76889,-63.83145,87.0,34096.394
13669,1,2000733.0,120040,1,21,5.0,4 a 7 anos,999992.0,0.0,0.0,...,9,18667,ATIVO,MUNIC,Porto Velho,Rondônia,-8.76889,-63.83145,87.0,34096.394
13670,1,2000733.0,120040,1,24,5.0,8 a 11 anos,999992.0,0.0,0.0,...,5,18687,ATIVO,MUNIC,Porto Velho,Rondônia,-8.76889,-63.83145,87.0,34096.394
13671,1,2000733.0,120040,1,24,5.0,4 a 7 anos,999992.0,2.0,0.0,...,9,18702,ATIVO,MUNIC,Porto Velho,Rondônia,-8.76889,-63.83145,87.0,34096.394
13736,1,2688611.0,355030,1,35,2.0,12 anos ou mais,10210.0,1.0,0.0,...,5,1066018,ATIVO,MUNIC,Porto Velho,Rondônia,-8.76889,-63.83145,87.0,34096.394

In [41]:
#Criando DF somente com as colunas necessárias

tarefa4_b = marco_2[['DTNASC', 'IDADEMAE', 'IDADEPAI']].copy()
tarefa4_b

           DTNASC  IDADEMAE  IDADEPAI
612    2019-03-09        19       NaN
700    2019-03-28        19       NaN
3232   2019-03-11        34       NaN
3238   2019-03-13        24       NaN
6818   2019-03-01        38      41.0
...           ...       ...       ...
13668  2019-03-20        19       NaN
13669  2019-03-25        21       NaN
13670  2019-03-21        24       NaN
13671  2019-03-22        24       NaN
13736  2019-03-07        35      42.0

[744 rows x 3 columns]

In [42]:
agrupamento = tarefa4_b.groupby(['DTNASC'])
agrupamento.agg([('Média','mean'), ('Máximo','max'), ('Mínimo','min')])
# Análise com DADOS FALTANTES - Optei por não excluir

             IDADEMAE                 IDADEPAI
                Média Máximo Mínimo      Média Máximo Mínimo
DTNASC
2019-03-01  28.343750     44     15  40.200000   51.0   33.0
2019-03-02  26.285714     38     14  32.000000   38.0   25.0
2019-03-03  28.285714     42     17  34.000000   34.0   34.0
2019-03-04  27.650000     43     16  33.800000   38.0   30.0
2019-03-05  26.000000     38     15  39.000000   39.0   39.0
2019-03-06  26.095238     37     16  35.000000   35.0   35.0
2019-03-07  27.350000     42     16  41.666667   52.0   31.0
2019-03-08  28.095238     42     17  31.000000   31.0   31.0
2019-03-09  24.777778     38     17  31.000000   37.0   26.0
2019-03-10  25.000000     39     16        NaN    NaN    NaN
2019-03-11  27.129032     41     15  32.250000   40.0   28.0
2019-03-12  28.222222     39     15        NaN    NaN    NaN
2019-03-13  26.333333     37     17  36.000000   37.0   35.0
2019-03-14  27.578947     42     16  31.000000   31.0   31.0
2019-03-15  27.088235     40     15  31.600000   38.0   23.0
2019-03-16  26.290323     44     16  26.333333   34.0   19.0
2019-03-17  24.500000     36     16  32.000000   40.0   24.0
2019-03-18  26.137931     40     14  34.666667   51.0   21.0
2019-03-19  29.043478     41     18  51.000000   53.0   49.0
2019-03-20  27.666667     43     18        NaN    NaN    NaN
2019-03-21  25.464286     40     15  44.000000   44.0   44.0
2019-03-22  26.736842     41     19  23.000000   23.0   23.0
2019-03-23  27.894737     40     16  29.000000   29.0   29.0
2019-03-24  25.391304     39     17  40.000000   55.0   30.0
2019-03-25  25.880000     38     16        NaN    NaN    NaN
2019-03-26  26.760000     40     17  27.000000   28.0   26.0
2019-03-27  27.680000     44     15  41.000000   62.0   20.0
2019-03-28  26.290323     40     16  35.666667   39.0   30.0
2019-03-29  24.880000     35     16        NaN    NaN    NaN
2019-03-30  28.368421     39     15        NaN    NaN    NaN
2019-03-31  22.352941     43     14        NaN    NaN    NaN

### Analise as respostas encontradas, tire algum insight delas, conte pra gente algo encontrado nos dados. Algo que você julgue relevante e novo pra você.

- A consulta "Média, Mínimo e Máximo de fihos vivos por dia do mês de março" confirma a ausência dos dados do pai em muitos registros de nascimentos. Seja por não registrarem os filhos, por morte do pai antes do nascimento do bebê, são vários fatores. Dependendo do objetivo da consulta, acredito que o NaN poderia ser substituído por 0 para não ser necessário excluir os registros das mães e influenciar na análise.

- A consulta "Qual município teve mais nascimentos" confirma que a capital do estado de Rondônia teve mais nascimentos. Uma análise mais detalhada seria o tamanho da população. Geralmente, a capital é mais populosa e por isso ter mais nascimentos. Outro indíce a ser avaliado em conjunto são as condições hospitalares da capital serem mais equipadas do que demais municípios, principalmente do interior.